// Structured reader for codex/General/class-subclass-index.md — that file is
// auto-generated by character-builder/scripts/generate-class-subclass-index.cjs
// with a fixed, predictable shape (one "## ClassName" section per class, each
// followed by an italic book summary and a "| Subclass | Edition | Source |
// Book |" table). Parsing it here instead of just rendering the raw markdown
// is what lets ClassSubclassIndexView filter/search it interactively.
//
// If the generator's output shape ever changes, update this parser to match.

const TOC_HEADING = '## สารบัญ class'

export function parseClassSubclassIndex(raw) {
  const lines = raw.split('\n')
  const tocIndex = lines.findIndex((l) => l.trim() === TOC_HEADING)
  const header = (tocIndex === -1 ? [] : lines.slice(0, tocIndex)).join('\n').trim()

  const classes = []
  let current = null
  let inTable = false

  for (let i = tocIndex === -1 ? 0 : tocIndex + 1; i < lines.length; i++) {
    const line = lines[i]

    const headingMatch = line.match(/^##\s+(.+)$/)
    if (headingMatch) {
      // Class headings are "## [Name](link)" (link to 5e.tools, or to this
      // project's own doc for a project-original class) — fall back to a
      // plain "## Name" read for safety if the generator ever emits one
      // unlinked.
      const linkMatch = headingMatch[1].trim().match(/^\[(.+)\]\((.+)\)$/)
      current = {
        name: linkMatch ? linkMatch[1].trim() : headingMatch[1].trim(),
        link: linkMatch ? linkMatch[2].trim() : null,
        summary: '',
        books: [],
        subclasses: [],
      }
      classes.push(current)
      inTable = false
      continue
    }
    if (!current) continue // still inside the TOC bullet list, before the first class heading

    if (line.startsWith('| Subclass |')) {
      inTable = true
      continue
    }
    if (line.startsWith('|---')) continue

    if (inTable && line.startsWith('|')) {
      const cells = line
        .split('|')
        .slice(1, -1)
        .map((c) => c.trim())
      if (cells.length < 4) continue
      const [subclassCell, edition, source, book] = cells
      const linkMatch = subclassCell.match(/^\[(.+)\]\((.+)\)$/)
      current.subclasses.push({
        name: linkMatch ? linkMatch[1] : subclassCell,
        link: linkMatch ? linkMatch[2] : null,
        edition,
        source,
        book,
      })
      continue
    }

    inTable = false
    const summaryMatch = line.match(/^_(.+)_$/)
    if (summaryMatch && !current.summary && current.subclasses.length === 0) {
      current.summary = summaryMatch[1].trim()
      // Generator joins a class's distinct source books with " + " (see
      // classBookSummary in generate-class-subclass-index.cjs) — split that
      // back out so the Book filter can match against the class itself, not
      // just its subclasses.
      current.books = current.summary.split('+').map((b) => b.trim())
    }
  }

  return { header, classes }
}
