// Structured reader for codex/General/00-sub-class-overview-tier-list-2024.md
// — auto-generated by character-builder/scripts/generate-subclass-overview-tier-list.cjs
// with a fixed, predictable shape: intro/legend/summary-count text, then one
// "## <Tier> Tier ... (<count>)" section per tier, each followed by a
// "| Subclass | Class | Source | หมายเหตุ |" table, then a closing
// "จุดสังเกตข้ามคลาส" section. Mirrors parseClassSubclassIndex.js's approach
// (see that file) but groups by tier instead of by class, and keeps
// whatever comes after the last tier group as a separate `footer` block
// instead of assuming groups run to the end of the file.
//
// If the generator's output shape ever changes, update this parser to match.

const TIER_HEADING_RE = /^##\s+([SABCD](?:\/[SABCD])*)\s+Tier.*\((\d+)\)\s*$/

export function parseSubclassTierOverview(raw) {
  const lines = raw.split('\n')
  const firstGroupIdx = lines.findIndex((l) => TIER_HEADING_RE.test(l.trim()))
  const header = (firstGroupIdx === -1 ? lines : lines.slice(0, firstGroupIdx)).join('\n').trim()

  const groups = []
  let current = null
  let inTable = false
  let footerStart = lines.length

  for (let i = firstGroupIdx === -1 ? lines.length : firstGroupIdx; i < lines.length; i++) {
    const line = lines[i]

    const headingMatch = line.match(/^##\s+(.+)$/)
    if (headingMatch) {
      const tierMatch = line.trim().match(TIER_HEADING_RE)
      if (tierMatch) {
        current = {
          tier: tierMatch[1],
          title: headingMatch[1].trim(),
          count: Number(tierMatch[2]),
          rows: [],
        }
        groups.push(current)
        inTable = false
        continue
      }
      // First non-tier "##" heading once groups have started (e.g. "จุดสังเกตข้ามคลาส") — everything from here on is the footer.
      footerStart = i
      break
    }
    if (!current) continue

    if (line.startsWith('| Subclass |')) {
      inTable = true
      continue
    }
    if (line.startsWith('|---')) continue

    if (inTable && line.startsWith('|')) {
      const cells = line
        .split('|')
        .slice(1, -1)
        .map((c) => c.trim())
      if (cells.length < 4) continue
      const [subclassCell, classCell, source, note] = cells
      const subMatch = subclassCell.match(/^\[(.+)\]\((.+)\)$/)
      const classMatch = classCell.match(/^\[(.+)\]\((.+)\)$/)
      current.rows.push({
        name: subMatch ? subMatch[1] : subclassCell,
        link: subMatch ? subMatch[2] : null,
        className: classMatch ? classMatch[1] : classCell,
        classLink: classMatch ? classMatch[2] : null,
        source,
        note,
      })
      continue
    }

    inTable = false
  }

  const footer = lines.slice(footerStart).join('\n').trim()

  return { header, groups, footer }
}
